---
title: "Dockerfile"
---

## High-level description
This Dockerfile builds a Docker image based on the `flipt/flipt:latest` image and installs additional tools like `git`, `bash`, and a script named `wait-for-it.sh`. This image is likely used for development or testing purposes, as it includes tools for interacting with Git repositories and a script for checking the availability of network services.

## Symbols
### `FROM flipt/flipt:latest`
#### Description
This line sets the base image for the Docker image to `flipt/flipt:latest`. This means the new image will inherit all the files, configurations, and software from the `flipt/flipt:latest` image.

### `USER root`
#### Description
This line switches the user context within the Docker image to the `root` user. This is done to ensure subsequent commands have the necessary permissions.

### `RUN apk update && apk add --no-cache git bash`
#### Description
This line installs the `git` and `bash` packages using the `apk` package manager. 
* `apk update` updates the package list cache.
* `apk add --no-cache git bash` installs the `git` and `bash` packages without using the cache.

### `RUN git clone https://github.com/vishnubob/wait-for-it.git /tmp &&     chmod +x /tmp/wait-for-it.sh`
#### Description
This line clones the `wait-for-it` repository from GitHub and makes the `wait-for-it.sh` script executable.
* `git clone https://github.com/vishnubob/wait-for-it.git /tmp` clones the repository into the `/tmp` directory.
* `chmod +x /tmp/wait-for-it.sh` makes the script executable.

## Dependencies
This Dockerfile relies on the `flipt/flipt:latest` Docker image as its base. It also downloads and uses the `wait-for-it` script from GitHub.
