---
title: "Dockerfile"
---

## High-level description
This Dockerfile builds a Docker image based on the `flipt/flipt:latest` image and installs the necessary dependencies for running Flipt with a CockroachDB database. 

It installs `git`, `bash`, and clones the `wait-for-it` script, which is a utility script to wait for other services to be available before proceeding.

## Symbols
### `FROM flipt/flipt:latest`
#### Description
This line specifies the base image for the Docker image being built. It uses the `flipt/flipt:latest` image from Docker Hub, which presumably contains the Flipt application.

### `USER root`
#### Description
This line switches the user context within the Docker image to the `root` user. This is done to perform subsequent commands with root privileges.

### `RUN apk update && apk add --no-cache git bash`
#### Description
This line installs the `git` and `bash` packages using the `apk` package manager, which is the package manager for Alpine Linux (the base OS for the `flipt/flipt:latest` image). 

* `apk update`: Updates the package index.
* `apk add --no-cache git bash`: Installs the `git` and `bash` packages without using the package cache.

### `RUN git clone https://github.com/vishnubob/wait-for-it.git /tmp &&     chmod +x /tmp/wait-for-it.sh`
#### Description
This line clones the `wait-for-it` repository from GitHub into the `/tmp` directory and makes the `wait-for-it.sh` script executable.

* `git clone https://github.com/vishnubob/wait-for-it.git /tmp`: Clones the repository.
* `chmod +x /tmp/wait-for-it.sh`: Makes the script executable.

## Dependencies
* **flipt/flipt:** This Docker image is the base image for this Dockerfile. It likely contains the Flipt application.
* **git:** Used to clone the `wait-for-it` repository.
* **bash:** Provides a Bourne-again shell environment within the Docker image.
* **wait-for-it:** A utility script used to wait for other services to become available before proceeding. This suggests that the Flipt application running in this container might depend on other services, like a CockroachDB instance. 
