---
title: "Dockerfile"
---

## High-level description
This Dockerfile builds a Docker image based on the `flipt/flipt:latest` image and installs the necessary dependencies for running Flipt with a MySQL database. It installs `git`, `bash`, and clones the `wait-for-it` script, which is a utility for waiting on the availability of a TCP host and port.

## Symbols
### `FROM flipt/flipt:latest`
#### Description
This line specifies the base image for the Docker image. It uses the `flipt/flipt:latest` image, which likely contains the Flipt application.

### `USER root`
#### Description
This line switches the user context within the Docker image to the `root` user. This is often required for performing operations that need elevated privileges, such as installing packages.

### `RUN apk update && apk add --no-cache git bash`
#### Description
This line installs the `git` and `bash` packages using the `apk` package manager, which is the package manager for Alpine Linux. The `--no-cache` option tells `apk` not to use the package cache.

### `RUN git clone https://github.com/vishnubob/wait-for-it.git /tmp &&     chmod +x /tmp/wait-for-it.sh`
#### Description
These lines clone the `wait-for-it` repository from GitHub into the `/tmp` directory and then make the `wait-for-it.sh` script executable. This script is commonly used in Dockerfiles to wait for services like databases to become available before proceeding. 
