---
title: "Dockerfile"
---

## High-level description
This Dockerfile builds a Docker image based on the `flipt/flipt:latest` image and adds PostgreSQL client tools and a script for waiting for network services. This image is likely used for running Flipt feature flag service with PostgreSQL as a database.

## Symbols
### `FROM flipt/flipt:latest`
#### Description
This line sets the base image for the Docker image being built to `flipt/flipt:latest`. This means the new image will inherit all the files, configurations, and settings from the `flipt/flipt:latest` image.

### `USER root`
#### Description
This line switches the user context within the Dockerfile to the `root` user. This is done to ensure that subsequent commands are executed with root privileges.

### `RUN apk update && apk add --no-cache git bash`
#### Description
This line installs the `git` and `bash` packages using the `apk` package manager. 
* `apk update` updates the package repository indexes.
* `apk add --no-cache git bash` installs the `git` and `bash` packages without caching the downloaded packages.

### `RUN git clone https://github.com/vishnubob/wait-for-it.git /tmp &&    chmod +x /tmp/wait-for-it.sh`
#### Description
This line clones the `wait-for-it` repository from GitHub into the `/tmp` directory and makes the `wait-for-it.sh` script executable.
* `git clone https://github.com/vishnubob/wait-for-it.git /tmp` clones the repository.
* `chmod +x /tmp/wait-for-it.sh` makes the script executable. The `wait-for-it` script is a useful utility for waiting for other services to become available before proceeding. This is often used in Docker environments to ensure that dependent services are ready. 
